# Generated by Django 2.2.6 on 2019-10-11 23:36

from django.db import migrations, models
import sharing.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField()),
                ('file', models.FileField(upload_to=sharing.utils.get_upload_path)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
