# Generated by Django 2.2.6 on 2019-10-12 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='burn_after',
            field=models.DurationField(blank=True, choices=[(None, 'Never'), (datetime.timedelta(seconds=600), '10 minutes'), (datetime.timedelta(seconds=3600), '1 hour'), (datetime.timedelta(days=1), '24 hours'), (datetime.timedelta(days=5), '5 days')], null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='burn_after_open',
            field=models.BooleanField(default=False, help_text='Expire link after it is visited once'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='message',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='short_identifier',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='filename',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
