# Generated by Django 2.2.6 on 2019-10-16 19:40

from django.db import migrations, models
import django.db.models.deletion
import sharing.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20191012_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='hash',
            new_name='file_hash',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='url_hash',
            field=models.CharField(default=sharing.utils.make_url_hash, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='short_identifier',
            field=models.SlugField(blank=True, help_text='[a-zA-Z0-9_-] only', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FileToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.SharedFile')),
            ],
        ),
    ]
